// =============================================================================
// Nemesis PostToolUse Hook — Output Audit Scanner (Unix)
// path: .nemesis/hooks/nemesis-posttool-check-unix.rs
// =============================================================================
//
// Scans content AFTER a tool executes — catches malicious code generated by
// the model before it lands in the developer's hands.
//
// POLICY:
//   - NEVER exits 2 — PostToolUse must not block (tool already ran)
//   - Prints WARNING to stderr when violations are found
//   - Writes all findings to .nemesis/logs/output-audit.log
//   - Always exits 0
//
// INPUT (stdin): PostToolUse JSON from IDE
//   Claude Code / OpenClaude format:
//     { "tool_name": "Write", "tool_input": { "file_path": "...", "content": "..." },
//       "tool_response": { ... } }
//   Devin format:
//     { "toolName": "write_to_file", "toolInput": { "path": "...", "content": "..." } }
//
// SCANNED FIELDS (in priority order):
//   Write/Edit  → tool_input.content / tool_input.new_string
//   Bash        → tool_response output string
//   Fallback    → full raw input as text
// =============================================================================

use std::io::Read;
use std::path::PathBuf;

fn main() {
    let mut raw = String::new();
    std::io::stdin().read_to_string(&mut raw).unwrap_or_default();

    if raw.trim().is_empty() {
        std::process::exit(0);
    }

    // Parse the PostToolUse JSON envelope
    let parsed: serde_json::Value = match serde_json::from_str(&raw) {
        Ok(v) => v,
        Err(_) => {
            // Not JSON — scan the raw text directly (e.g. plain code piped in)
            scan_and_report(&raw, "raw-input");
            std::process::exit(0);
        }
    };

    // Extract tool name for log context
    let tool_name = parsed.get("tool_name")
        .or_else(|| parsed.get("toolName"))
        .and_then(|v| v.as_str())
        .unwrap_or("unknown")
        .to_string();

    // Extract the most relevant content fields
    let mut candidates: Vec<(&str, String)> = Vec::new();

    let tool_input = parsed.get("tool_input")
        .or_else(|| parsed.get("toolInput"));

    if let Some(input) = tool_input {
        // Write tool: content field
        if let Some(content) = input.get("content").and_then(|v| v.as_str()) {
            candidates.push(("tool_input.content", content.to_string()));
        }
        // Edit tool: new_string field
        if let Some(ns) = input.get("new_string").and_then(|v| v.as_str()) {
            candidates.push(("tool_input.new_string", ns.to_string()));
        }
        // Bash tool: command field
        if let Some(cmd) = input.get("command").and_then(|v| v.as_str()) {
            candidates.push(("tool_input.command", cmd.to_string()));
        }
        // Generic path field for context
        if let Some(path_val) = input.get("file_path")
            .or_else(|| input.get("path"))
            .and_then(|v| v.as_str())
        {
            candidates.push(("tool_input.file_path", path_val.to_string()));
        }
    }

    // Tool response output (Bash stdout/stderr)
    let tool_response = parsed.get("tool_response");
    if let Some(resp) = tool_response {
        if let Some(output) = resp.as_str() {
            candidates.push(("tool_response", output.to_string()));
        } else if let Some(output) = resp.get("output").and_then(|v| v.as_str()) {
            candidates.push(("tool_response.output", output.to_string()));
        }
    }

    // If no structured fields found, scan the full raw input
    if candidates.is_empty() {
        scan_and_report(&raw, &tool_name);
        std::process::exit(0);
    }

    // Scan each extracted field
    for (field, content) in &candidates {
        if !content.trim().is_empty() {
            scan_and_report(content, &format!("{}:{}", tool_name, field));
        }
    }

    std::process::exit(0);
}

fn scan_and_report(content: &str, context: &str) {
    let virtual_path = PathBuf::from("output-audit.txt");
    let result = nemesis_defender::scan_content(&virtual_path, content.as_bytes());

    if result.violations.is_empty() {
        return;
    }

    let severity_tag = match result.severity {
        nemesis_defender::Severity::Malicious  => "MALICIOUS",
        nemesis_defender::Severity::Suspicious => "SUSPICIOUS",
        nemesis_defender::Severity::Clean      => return,
    };

    eprintln!(
        "[NEMESIS OUTPUT AUDIT] {} — {} violation(s) in model output [{}]",
        severity_tag,
        result.violations.len(),
        context
    );
    for v in &result.violations {
        eprintln!("  ├─ [{}] {}", v.visitor, v.message);
        if let Some(ref suggestion) = v.suggestion {
            eprintln!("  │   → FIX: {}", suggestion);
        }
    }
    eprintln!("  └─ WARNING: Model-generated content contains suspicious patterns. Review before use.");

    write_audit_log(&result, context, content);
}

fn write_audit_log(result: &nemesis_defender::DefenderResult, context: &str, content: &str) {
    let log_dir = resolve_log_dir();
    if let Err(e) = std::fs::create_dir_all(&log_dir) {
        eprintln!("[NEMESIS OUTPUT AUDIT] Cannot create log dir: {}", e);
        return;
    }

    let log_path = log_dir.join("output-audit.log");
    let timestamp = chrono::Local::now().format("%Y-%m-%dT%H:%M:%S");

    let mut entries = String::new();
    entries.push_str(&format!("\n[{}] context={} severity={:?} violations={}\n",
        timestamp, context, result.severity, result.violations.len()));

    for v in &result.violations {
        entries.push_str(&format!("  ├─ visitor={} evidence={:?}\n", v.visitor, v.evidence));
        entries.push_str(&format!("  │   message={}\n", v.message));
        if let Some(ref s) = v.suggestion {
            entries.push_str(&format!("  │   fix={}\n", s));
        }
    }

    // Truncate scanned content preview to 200 chars for log readability
    let preview: String = content.chars().take(200).collect();
    entries.push_str(&format!("  └─ content_preview={:?}\n", preview));

    use std::io::Write;
    match std::fs::OpenOptions::new().create(true).append(true).open(&log_path) {
        Ok(mut f) => { let _ = f.write_all(entries.as_bytes()); }
        Err(e) => { eprintln!("[NEMESIS OUTPUT AUDIT] Log write failed: {}", e); }
    }
}

fn resolve_log_dir() -> PathBuf {
    // Try CWD-relative path first (binary invoked from project root)
    let cwd = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
    let candidate = cwd.join(".nemesis").join("logs");
    if candidate.parent().map(|p| p.exists()).unwrap_or(false) {
        return candidate;
    }
    // Fallback: same directory as the binary
    std::env::current_exe()
        .ok()
        .and_then(|p| p.parent().map(|d| d.join("logs")))
        .unwrap_or_else(|| PathBuf::from(".nemesis/logs"))
}
