/// AST Linters — Validação semântica de código via tree-sitter.
///
/// Este crate fornece um pipeline de validação semântica que complementa
/// as validações regex do `workflow_enforcer`. Usa tree-sitter para
/// parsear código-fonte e visitadores para detectar violações que
/// regex não consegue capturar.
///
/// # Uso típico
///
/// ```ignore
/// use ast_linters::validator::validate_semantic;
/// let violations = validate_semantic(content, file_path);
/// ```

pub mod language;
pub mod parser;
pub mod cache;
pub mod validator;
pub mod lint_rule;
pub mod rule_registry;
pub mod rule_wrappers;

pub mod visitors;
pub mod semantic;

// Auto-generated by build.rs from rules.toml
include!(concat!(env!("OUT_DIR"), "/generated_visitors.rs"));
