/// Codegen para gerar visitors Rust a partir da DSL TOML.
///
/// Este script lê o arquivo rules.toml e gera código Rust para os visitors.

use std::collections::HashMap;
use std::fs;
use std::path::Path;

#[derive(Debug, serde::Deserialize)]
struct RuleConfig {
    query: String,
    message: String,
    severity: String,
    category: Option<String>,
    languages: Vec<String>,
    suggestion: Option<String>,
}

#[derive(Debug, serde::Deserialize)]
struct RulesToml {
    rule: HashMap<String, RuleConfig>,
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("cargo:rerun-if-changed=rules.toml");
    
    let rules_path = Path::new("rules.toml");
    let content = fs::read_to_string(rules_path)?;
    let rules: RulesToml = toml::from_str(&content)?;
    
    let mut generated_code = String::new();
    
    // Header do arquivo gerado
    generated_code.push_str("// Auto-generated by build.rs from rules.toml\n");
    generated_code.push_str("// DO NOT EDIT MANUALLY\n\n");
    generated_code.push_str("use crate::lint_rule::{LintRule, Context, Severity, Violation, RuleCategory};\n");
    generated_code.push_str("use crate::parser::ParsedTree;\n");
    generated_code.push_str("use streaming_iterator::StreamingIterator;\n\n");
    
    // Gerar um visitor para cada regra
    for (rule_name, rule_config) in &rules.rule {
        let struct_name = format!("{}Visitor", to_pascal_case(rule_name));
        let query = &rule_config.query;
        let message = &rule_config.message;
        let severity = match rule_config.severity.as_str() {
            "error" => "Severity::Error",
            "warning" => "Severity::Warning",
            _ => "Severity::Error",
        };
        let category = match rule_config.category.as_deref() {
            Some("suspicious") => "RuleCategory::Suspicious",
            Some("security") => "RuleCategory::Security",
            Some("style") => "RuleCategory::Style",
            _ => "RuleCategory::Correctness",
        };
        let suggestion_code = match &rule_config.suggestion {
            Some(s) => format!(".with_suggestion(\"{}\")", s),
            None => String::new(),
        };
        
        // Mapear nomes de linguagem para variantes de Language
        let languages: Vec<String> = rule_config.languages.iter()
            .map(|lang| match lang.as_str() {
                "typescript" => "TypeScript",
                "tsx" => "TypeScriptReact",
                "javascript" => "JavaScript",
                "jsx" => "JavaScriptReact",
                "python" => "Python",
                "go" => "Go",
                "java" => "Java",
                "rust" => "Rust",
                _ => lang,
            })
            .map(|lang| format!("crate::language::Language::{}", lang))
            .collect();
        
        generated_code.push_str(&format!(r#"
#[derive(Debug)]
pub struct {struct_name} {{
    query: String,
    message: String,
}}

impl {struct_name} {{
    pub fn new() -> Self {{
        Self {{
            query: "{query}".to_string(),
            message: "{message}".to_string(),
        }}
    }}
}}

impl LintRule for {struct_name} {{
    fn name(&self) -> &str {{
        "{rule_name}"
    }}

    fn category(&self) -> RuleCategory {{
        {category}
    }}
    
    fn default_severity(&self) -> Severity {{
        {severity}
    }}
    
    fn supported_languages(&self) -> &[crate::language::Language] {{
        &[
{}
        ]
    }}
    
    fn should_run(&self, language: crate::language::Language) -> bool {{
        self.supported_languages().contains(&language)
    }}
    
    fn visit(&self, tree: &ParsedTree, ctx: &Context) -> Vec<Violation> {{
        let mut violations = Vec::new();
        let query = match tree_sitter::Query::new(
            &tree.tree.language(),
            &self.query,
        ) {{
            Ok(q) => q,
            Err(e) => {{
                eprintln!("[AST-LINTERS] Query compile error for rule '{rule_name}': {{:?}}", e);
                return violations;
            }}
        }};
        let mut cursor = tree_sitter::QueryCursor::new();
        let mut matches = cursor.matches(&query, tree.tree.root_node(), ctx.source.as_bytes());
        while let Some(m) = matches.next() {{
            for capture in m.captures {{
                let line = capture.node.start_position().row + 1;
                violations.push(
                    Violation::new(
                        self.message.clone(),
                        line,
                        {category},
                    )
                    .with_rule_name("{rule_name}")
                    .with_severity({severity})
                    {suggestion_code}
                );
            }}
        }}
        violations
    }}
}}

"#, languages.join(",\n        ")));
    }
    
    // Função para registrar todos os visitors gerados
    generated_code.push_str("\npub fn register_generated_rules(registry: &mut crate::rule_registry::RuleRegistry) {\n");
    for rule_name in rules.rule.keys() {
        let struct_name = format!("{}Visitor", to_pascal_case(rule_name));
        generated_code.push_str(&format!("    registry.register(Box::new({}::new()));\n", struct_name));
    }
    generated_code.push_str("}\n");
    
    // Escrever o código gerado em OUT_DIR
    let out_dir = std::env::var("OUT_DIR")?;
    let output_path = Path::new(&out_dir).join("generated_visitors.rs");
    fs::write(&output_path, generated_code)?;
    
    println!("cargo:warning=Generated {} visitors from rules.toml", rules.rule.len());
    println!("cargo:warning=Output path: {:?}", output_path);
    
    Ok(())
}

fn to_pascal_case(s: &str) -> String {
    s.split('-')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect()
}

fn to_camel_case(s: &str) -> String {
    s.split('-')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect()
}
